# Site settings
title: Daisuke Kuwabara
description: >- 
  Xoogler
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://babushkai.com"

twitter_username: kwDaisuke
github_username: babushkai

# Build settings
theme: minima
plugins:
  - jekyll-feed

language_default: en

# Collections
collections:
  en:
    output: true
    permalink: /en/:slug
  jp:
    output: true
    permalink: /jp/:slug

# Defaults
defaults:
  - scope:
      type: "en"
    values:
      layout: "page"
  - scope:
      type: "jp"
    values:
      layout: "page"

# Exclude unnecessary files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
